### Problem 1 ###

In [1]:
import numpy as np
import torch 

In [2]:
x = np.genfromtxt("C:\\Users\\sraba\\OneDrive\\Documents\\ML_Barbu\\Datasets\\hmm_pb1.csv", delimiter=',',dtype=int)

In [3]:
x

array([1, 2, 5, 5, 1, 3, 6, 3, 2, 3, 6, 6, 1, 3, 3, 2, 3, 4, 3, 1, 2, 2,
       4, 2, 5, 6, 3, 2, 1, 5, 5, 2, 2, 5, 3, 4, 1, 6, 6, 1, 5, 5, 2, 6,
       2, 1, 1, 3, 6, 1, 4, 3, 1, 2, 2, 6, 3, 3, 1, 2, 1, 6, 4, 3, 2, 3,
       1, 1, 5, 1, 2, 4, 1, 3, 2, 6, 1, 6, 6, 1, 6, 6, 5, 4, 6, 5, 2, 3,
       3, 1, 5, 6, 2, 6, 3, 6, 6, 3, 3, 3, 6, 6, 6, 6, 5, 1, 2, 6, 6, 6,
       2, 6, 6, 6, 3, 5, 2, 6, 3, 6, 2, 6, 6, 1, 3, 1, 1, 4, 5, 6, 2, 3,
       1, 3, 6, 2, 6, 6, 3, 5, 4, 5, 6, 3, 3, 2, 6, 2, 6, 3, 3, 2, 5, 3,
       6, 5, 3, 5, 2, 1, 3, 6, 2, 5, 5, 1, 6, 6, 6, 6, 1, 5, 2, 4, 6, 1,
       2, 4, 3, 1, 3, 3, 1, 2, 2, 6, 6, 6, 5, 4, 3, 3, 3, 6, 3, 2, 2, 3,
       1, 4, 5, 5, 2, 5, 4, 3, 1, 6, 1, 2, 6, 4, 2, 6, 6, 3, 1, 2, 6, 5,
       5, 6, 6, 6, 6, 6, 6, 6, 3, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 4,
       4, 6, 6, 2, 2, 6, 6, 3, 6, 6, 2, 5, 6, 3, 6, 4, 4, 6, 6, 6, 6, 2,
       4, 6, 2, 6, 6, 6, 6, 6, 6, 4, 3])

In [4]:
x.shape

(275,)

In [5]:
a_k = torch.tensor([[0.9500, 0.0500], [0.0500, 0.9500]])
b_k = torch.tensor([[1/6, 1/6, 1/6, 1/6, 1/6, 1/6], [1/10, 1/10, 1/10, 1/10, 1/10, 1/2]])
Pi_k = torch.tensor([0.5, 0.5])

In [6]:
a_k

tensor([[0.9500, 0.0500],
        [0.0500, 0.9500]])

In [7]:
b_k

tensor([[0.1667, 0.1667, 0.1667, 0.1667, 0.1667, 0.1667],
        [0.1000, 0.1000, 0.1000, 0.1000, 0.1000, 0.5000]])

In [8]:
Pi_k

tensor([0.5000, 0.5000])

In [9]:
def viterbi(x,a_k,b_k,Pi_k):
    
    C_k = torch.zeros(2,x.size)
    P_tr_k = torch.zeros(2,x.size).long()
    C_k[:,0] = torch.log(b_k[:,x[0]]*Pi_k)
    
    for t in range(1,x.size):
        for k in range(2):
            maximizing_portion = torch.log(a_k[:,k]) + C_k[:,t-1]
            C_k[k,t] = torch.log(b_k[k,x[t]-1]) + torch.max(maximizing_portion)
            P_tr_k[k,t] = torch.argmax(maximizing_portion)
            
    P = torch.exp(torch.max(C_k,1).values)
    
    y=torch.ones(x.size).long()
    y[x.size-1]=torch.argmax(C_k[:,x.size-1]) + 1
    for t in range(x.size-1,0,-1):
        y[t-1]=P_tr_k[y[t]-1,t] + 1
    return y

In [10]:
y = viterbi(x,a_k,b_k,Pi_k)

In [11]:
y

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [12]:
def FWD(x,a_k,b_k,Pi_k):
    alpha=torch.zeros(2,x.size)
    alpha[:,0]=b_k[:,x[0]-1]*Pi_k
    for t in range(1,x.size):
        alpha[:,t] = b_k[:,x[t]-1]*(a_k@alpha[:,t-1])
        alpha[:,t] = alpha[:,t]/torch.sum(alpha[:,t])
    return alpha

In [13]:
def BWD(x,a_k,b_k):
    beta=torch.ones(2,x.size)
    for t in range(x.size-2,-1,-1):
        beta[:,t] = a_k@(b_k[:,x[t+1]-1]*beta[:,t+1])
        beta[:,t] = beta[:,t]/torch.sum(beta[:,t])
    return beta

In [14]:
alpha = FWD(x,a_k,b_k,Pi_k)
beta = BWD(x,a_k,b_k)

In [15]:
alpha[0,118]/alpha[1,118]

tensor(0.4383)

In [16]:
beta[0,118]/beta[1,118]

tensor(0.3913)

### Problem 2 ###

In [17]:
x_next = np.genfromtxt("C:\\Users\\sraba\\OneDrive\\Documents\\ML_Barbu\\Datasets\\hmm_pb2.csv", delimiter=',',dtype=int)

In [18]:
x_next

array([6, 4, 2, ..., 1, 3, 3])

In [19]:
a = a_k.clone()
b = b_k.clone()
Pi = torch.tensor([0.7, 0.3])

In [20]:
for n in range(1001):

    alpha = FWD(x_next,a,b,Pi)
    beta = BWD(x_next,a,b)

    xi_t = alpha[:,0:x_next.size-1].unsqueeze(1)*a.unsqueeze(2)*beta[:,1:x_next.size].unsqueeze(0)*b[:,x_next[1:x_next.size]-1].unsqueeze(0)
    xi_t = xi_t/torch.sum(xi_t,(0,1),keepdim=True)

    gamma_t = alpha*beta
    gamma_t = gamma_t/torch.sum(gamma_t,axis=0,keepdim=True)

    Pi = gamma_t[:,0]
    
    gamma_t1 = gamma_t[:,0:9999].unsqueeze(1)
    a = torch.sum(xi_t,axis=2)/torch.sum(gamma_t1,axis=2)

    for l in range(b.shape[1]):
        b[:, l] = torch.sum(gamma_t[:,x_next-1 == l], axis=1)
    b = b/torch.sum(gamma_t, axis=1).reshape(-1,1)
    
#    print(a,"\n",b,"\n",Pi)

In [21]:
Pi

tensor([1.0000e+00, 2.3822e-44])

In [22]:
a

tensor([[0.8639, 0.1361],
        [0.1433, 0.8567]])

In [23]:
b

tensor([[0.2301, 0.2111, 0.1912, 0.2293, 0.0486, 0.0898],
        [0.1633, 0.1929, 0.1860, 0.1614, 0.1998, 0.0966]])